version: 2

builds:
  - main: ./cmd
    binary: lunar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

dockers_v2:
  - images:
      - "dimiro1/lunar"
    tags:
      - "v{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: goreleaser.Dockerfile

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
