// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package diff

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/dimiro1/faas-go/internal/ui/components/card"
	"github.com/dimiro1/faas-go/internal/ui/components/preview"
)

func Preview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
						templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
						if !templ_7745c5c3_IsBuffer {
							defer func() {
								templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err == nil {
									templ_7745c5c3_Err = templ_7745c5c3_BufErr
								}
							}()
						}
						ctx = templ.InitializeContext(ctx)
						templ_7745c5c3_Err = VersionLabelsWithProps(VersionLabelProps{
							OldLabel:  "Version 2",
							NewLabel:  "Version 3",
							OldMeta:   "2 days ago",
							NewMeta:   "just now",
							Additions: 3,
							Deletions: 2,
						}).Render(ctx, templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						return nil
					})
					templ_7745c5c3_Err = card.Header(card.HeaderProps{Title: "Code Changes"}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
						templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
						if !templ_7745c5c3_IsBuffer {
							defer func() {
								templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err == nil {
									templ_7745c5c3_Err = templ_7745c5c3_BufErr
								}
							}()
						}
						ctx = templ.InitializeContext(ctx)
						templ_7745c5c3_Err = Viewer(Props{MaxHeight: "300px", NoBorder: true, Language: "lua"}, []Line{
							{OldLine: 1, NewLine: 1, Type: LineUnchanged, Content: "function handler(ctx, event)"},
							{OldLine: 2, NewLine: 0, Type: LineRemoved, Content: "  -- Parse query parameters"},
							{OldLine: 0, NewLine: 2, Type: LineAdded, Content: "  -- Parse query parameters from event"},
							{OldLine: 3, NewLine: 3, Type: LineUnchanged, Content: "  local name = \"World\""},
							{OldLine: 4, NewLine: 0, Type: LineRemoved, Content: "  if ctx.query and ctx.query.name then"},
							{OldLine: 5, NewLine: 0, Type: LineRemoved, Content: "    name = ctx.query.name"},
							{OldLine: 0, NewLine: 4, Type: LineAdded, Content: "  if event.query and event.query.name then"},
							{OldLine: 0, NewLine: 5, Type: LineAdded, Content: "    name = event.query.name"},
							{OldLine: 6, NewLine: 6, Type: LineUnchanged, Content: "  end"},
							{OldLine: 7, NewLine: 7, Type: LineUnchanged, Content: ""},
							{OldLine: 8, NewLine: 8, Type: LineUnchanged, Content: "  log.info(\"Greeting: \" .. name)"},
							{OldLine: 9, NewLine: 9, Type: LineUnchanged, Content: ""},
							{OldLine: 10, NewLine: 10, Type: LineUnchanged, Content: "  return {"},
							{OldLine: 11, NewLine: 11, Type: LineUnchanged, Content: "    statusCode = 200,"},
							{OldLine: 12, NewLine: 12, Type: LineUnchanged, Content: "    headers = { [\"Content-Type\"] = \"application/json\" },"},
							{OldLine: 13, NewLine: 13, Type: LineUnchanged, Content: "    body = json.encode({ message = \"Hello, \" .. name .. \"!\" })"},
							{OldLine: 14, NewLine: 14, Type: LineUnchanged, Content: "  }"},
							{OldLine: 15, NewLine: 15, Type: LineUnchanged, Content: "end"},
						}).Render(ctx, templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						return nil
					})
					templ_7745c5c3_Err = card.Content(card.ContentProps{NoPadding: true}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = card.Card(card.Props{}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = preview.Section("In Card with Header").Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var7 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = Viewer(Props{MaxHeight: "300px", Language: "lua"}, []Line{
					{OldLine: 1, NewLine: 1, Type: LineUnchanged, Content: "local json = require(\"json\")"},
					{OldLine: 2, NewLine: 2, Type: LineUnchanged, Content: ""},
					{OldLine: 3, NewLine: 3, Type: LineUnchanged, Content: "-- Main entry point"},
					{OldLine: 4, NewLine: 4, Type: LineUnchanged, Content: "function handler(ctx, event)"},
					{OldLine: 5, NewLine: 0, Type: LineRemoved, Content: "  print(\"Old version\")"},
					{OldLine: 0, NewLine: 5, Type: LineAdded, Content: "  print(\"New version\")"},
					{OldLine: 6, NewLine: 6, Type: LineUnchanged, Content: ""},
					{OldLine: 7, NewLine: 7, Type: LineUnchanged, Content: "  local response = {"},
					{OldLine: 8, NewLine: 0, Type: LineRemoved, Content: "    message = \"Hello\""},
					{OldLine: 0, NewLine: 8, Type: LineAdded, Content: "    message = \"Hello World!\","},
					{OldLine: 0, NewLine: 9, Type: LineAdded, Content: "    timestamp = os.time()"},
					{OldLine: 9, NewLine: 10, Type: LineUnchanged, Content: "  }"},
					{OldLine: 10, NewLine: 11, Type: LineUnchanged, Content: ""},
					{OldLine: 11, NewLine: 12, Type: LineUnchanged, Content: "  return response"},
					{OldLine: 12, NewLine: 13, Type: LineUnchanged, Content: "end"},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = preview.Section("Basic Diff").Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var8 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = Viewer(Props{MaxHeight: "200px", Language: "go"}, []Line{
					{OldLine: 1, NewLine: 1, Type: LineUnchanged, Content: "package main"},
					{OldLine: 2, NewLine: 2, Type: LineUnchanged, Content: ""},
					{OldLine: 3, NewLine: 3, Type: LineUnchanged, Content: "import ("},
					{OldLine: 4, NewLine: 0, Type: LineRemoved, Content: "    \"fmt\""},
					{OldLine: 0, NewLine: 4, Type: LineAdded, Content: "    \"fmt\""},
					{OldLine: 0, NewLine: 5, Type: LineAdded, Content: "    \"log\""},
					{OldLine: 0, NewLine: 6, Type: LineAdded, Content: "    \"time\""},
					{OldLine: 5, NewLine: 7, Type: LineUnchanged, Content: ")"},
					{OldLine: 6, NewLine: 8, Type: LineUnchanged, Content: ""},
					{OldLine: 7, NewLine: 9, Type: LineUnchanged, Content: "func main() {"},
					{OldLine: 8, NewLine: 0, Type: LineRemoved, Content: "    fmt.Println(\"Hello\")"},
					{OldLine: 0, NewLine: 10, Type: LineAdded, Content: "    log.Printf(\"Starting at %v\", time.Now())"},
					{OldLine: 0, NewLine: 11, Type: LineAdded, Content: "    fmt.Println(\"Hello, World!\")"},
					{OldLine: 9, NewLine: 12, Type: LineUnchanged, Content: "}"},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = preview.Section("Large Diff with Scroll").Render(templ.WithChildren(ctx, templ_7745c5c3_Var8), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var9 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = Viewer(Props{MaxHeight: "150px", Language: "javascript"}, []Line{
					{OldLine: 1, NewLine: 1, Type: LineUnchanged, Content: "// Config"},
					{OldLine: 0, NewLine: 2, Type: LineAdded, Content: "const DEBUG = true"},
					{OldLine: 0, NewLine: 3, Type: LineAdded, Content: "const VERSION = \"1.0.0\""},
					{OldLine: 0, NewLine: 4, Type: LineAdded, Content: "const TIMEOUT = 30"},
					{OldLine: 2, NewLine: 5, Type: LineUnchanged, Content: ""},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = preview.Section("Only Additions").Render(templ.WithChildren(ctx, templ_7745c5c3_Var9), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var10 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = Viewer(Props{MaxHeight: "150px", Language: "javascript"}, []Line{
					{OldLine: 1, NewLine: 1, Type: LineUnchanged, Content: "// Deprecated functions"},
					{OldLine: 2, NewLine: 0, Type: LineRemoved, Content: "function oldFunction() {}"},
					{OldLine: 3, NewLine: 0, Type: LineRemoved, Content: "function legacyHandler() {}"},
					{OldLine: 4, NewLine: 0, Type: LineRemoved, Content: "function deprecatedApi() {}"},
					{OldLine: 5, NewLine: 2, Type: LineUnchanged, Content: ""},
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = preview.Section("Only Deletions").Render(templ.WithChildren(ctx, templ_7745c5c3_Var10), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = preview.Page(preview.PreviewPageProps{
			Title:       "Diff",
			Description: "Code diff viewer for comparing versions.",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
